### ISSUE TITLE
Add Initialization Commands to .gitpod.yml

### ISSUE THREAD

**Issue by kdelfour** [maxds-lyon/Kata-Terraform#1]
In order to streamline the setup process for our development environment, we need to add additional initialization commands to the `.gitpod.yml` file. This will ensure that all necessary configurations, such as AWS region and credentials, are set up automatically when a Gitpod workspace is started.

The following tasks should be added to the `.gitpod.yml` file:
```
tasks:
  - name: Start LocalStack
    init: localstack start -d
  - name: AWS configure Region and Credential
    init: aws configure set default.region us-east-1 &&  aws configure set  aws_access_key_id none &&  aws configure set aws_secret_access_key none
```

This will help in avoiding manual configuration steps and make our development process more efficient.
